### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by Qodestackr** [harryheman/screen-record#1]
Hey @harryheman, nice app:
However, I'm experiencing:
``` SyntaxError: The requested module 'buffer' does not provide an export named 'Blob'  ```

**Comment by harryheman** [comment]
Hello, my friend. Thanks. You need to update your Node.js ([`Blob was added in v15.7.0, v14.18.0`](https://nodejs.org/api/buffer.html#class-blob)) or use [`cross-blob`](https://www.npmjs.com/package/cross-blob) instead of 'buffer'

**Comment by Qodestackr** [comment]
Thanks
